"""Midori - OCP primitive auto-generated by OCP-agent. Self-contained,
version-parameterized (version = [block_bitsize, key_bitsize], like present.py/led.py).
Versions: Midori64 (64, 128)."""
from primitives.primitives import Block_cipher
from operators.Sbox import Midori_Sb0_Sbox, Midori_Sb1_Sbox
from operators.boolean_operators import XOR
import variables.variables as var

MIDORI_VERSIONS = {(64, 128): {'wb': 4, 'nw': 16, 'kwb': 4, 'knw': 32}}
MIDORI_DEFAULT = (64, 128)


def _midori_sel(version):
    sel = tuple(version) if isinstance(version, (list, tuple)) else None
    if sel not in MIDORI_VERSIONS:
        raise ValueError(f"unsupported Midori version {version!r}; expected "
                         f"one of {[list(v) for v in MIDORI_VERSIONS]}")
    return sel


class Midori_block_cipher(Block_cipher):
    def __init__(self, name, version, p_input, k_input, c_output, nbr_rounds=None):
        sel = _midori_sel(version)
        if sel == (64, 128):
            if nbr_rounds is None: nbr_rounds = 17
            s_config = [5, 16, 0, 4]
            k_config = [1, 32, 0, 4]
            sk_config = [2, 16, 16, 4]
            super().__init__(name, p_input, k_input, c_output, nbr_rounds, nbr_rounds, s_config, k_config, sk_config)
            S = self.functions["PERMUTATION"]
            KS = self.functions["KEY_SCHEDULE"]
            SK = self.functions["SUBKEYS"]
            for i in range(1, nbr_rounds + 1):
                _phases = [{'xor': [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]]}, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], {'xor': [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]]}]
                e = _phases[(i - 1) % 17]
                if isinstance(e, dict):
                    flat = [idx for sh in e['xor'] for idx in sh]
                    SK.ExtractionLayer('SK_EX', i, 0, flat, KS.vars[i][0])
                    SK.SingleOperatorLayer('SK_XOR', i, 1, XOR, [[j, 16 + j] for j in range(16)], list(range(16)))
                else:
                    SK.ExtractionLayer('SK_EX', i, 0, list(e) * 2, KS.vars[i][0])
                    SK.AddIdentityLayer('SK_ID', i, 1)
            for i in range(1, nbr_rounds):
                KS.AddIdentityLayer("K_ID", i, 0)
            for i in range(1, nbr_rounds + 1):
                S.AddRoundKeyLayer("ARK_0", i, 0, XOR, SK, mask=[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
                if i not in {1, 17}:
                    S.AddConstantLayer("C_1", i, 1, 'xor', [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1], [0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0], [1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1], [0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1], [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1], [1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0], [0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0], [1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1], [0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0], [0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1], [0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0], [0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0], [1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0], [1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
                else:
                    S.AddIdentityLayer("ID_1", i, 1)
                if i not in {17}:
                    S.SboxLayer("SB_2", i, 2, Midori_Sb0_Sbox, mask=None, index=[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15]])
                else:
                    S.AddIdentityLayer("ID_2", i, 2)
                if i not in {16, 17}:
                    S.PermutationLayer("P_3", i, 3, [0, 10, 5, 15, 14, 4, 11, 1, 9, 3, 12, 6, 7, 13, 2, 8])
                else:
                    S.AddIdentityLayer("ID_3", i, 3)
                if i not in {16, 17}:
                    S.MatrixLayer("MAT_4", i, 4, [[0, 1, 1, 1], [1, 0, 1, 1], [1, 1, 0, 1], [1, 1, 1, 0]], [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]], polynomial='0x0')
                else:
                    S.AddIdentityLayer("ID_4", i, 4)
        else:
            raise ValueError(f"unsupported version {version}")
        self.gen_test_vectors(version)

    def gen_test_vectors(self, version):
        self.test_vectors = []
        sel = _midori_sel(version)
        if sel == (64, 128):
            plaintext = [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            ]
            key = [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            ]
            ciphertext = [
                3, 12, 9, 12, 12, 14, 13, 10, 2, 11, 11, 13, 4, 4, 9, 10
            ]
            self.test_vectors.append([[plaintext, key], ciphertext])
            plaintext = [
                4, 2, 12, 2, 0, 15, 13, 3, 11, 5, 8, 6, 8, 7, 9, 14
            ]
            key = [
                6, 8, 7, 13, 14, 13, 3, 11, 3, 12, 8, 5, 11, 3, 15, 3,
                5, 11, 1, 0, 0, 9, 8, 6, 3, 14, 2, 10, 8, 12, 11, 15
            ]
            ciphertext = [
                6, 6, 11, 12, 13, 12, 6, 2, 7, 0, 13, 9, 0, 1, 12, 13
            ]
            self.test_vectors.append([[plaintext, key], ciphertext])


def MIDORI_BLOCKCIPHER(r=None, version=None, copy_operator=False):
    if version is None: version = MIDORI_DEFAULT
    v = MIDORI_VERSIONS[_midori_sel(version)]
    p = [var.Variable(v["wb"], ID="p" + str(i)) for i in range(v["nw"])]
    k = [var.Variable(v["kwb"], ID="k" + str(i)) for i in range(v["knw"])]
    c = [var.Variable(v["wb"], ID="c" + str(i)) for i in range(v["nw"])]
    cipher = Midori_block_cipher("Midori", version, p, k, c, nbr_rounds=r)
    cipher.post_initialization(copy_operator=copy_operator)
    return cipher
