"""TinyARX - OCP primitive auto-generated by OCP-agent from a user cipher
definition. Self-contained (no agent deps). Round: rotation; modadd; rotation; xor."""
from primitives.primitives import Permutation
from operators.boolean_operators import XOR
from operators.modular_operators import ModAdd
import variables.variables as var


class TinyARX_permutation(Permutation):
    def __init__(self, name, s_input, s_output, nbr_rounds=None):
        if nbr_rounds is None: nbr_rounds = 2
        super().__init__(name, s_input, s_output, nbr_rounds, [4, 2, 0, 16])
        S = self.functions["PERMUTATION"]
        for i in range(1, nbr_rounds + 1):
            S.RotationLayer("ROT_0", i, 0, ['r', 7, 0])
            S.SingleOperatorLayer("MODADD_1", i, 1, ModAdd, [[0, 1]], [0])
            S.RotationLayer("ROT_2", i, 2, ['l', 2, 1])
            S.SingleOperatorLayer("XOR_3", i, 3, XOR, [[0, 1]], [1])


def TINYARX_PERMUTATION(r=None, version=None, copy_operator=False):
    inp = [var.Variable(16, ID="in" + str(i)) for i in range(2)]
    out = [var.Variable(16, ID="out" + str(i)) for i in range(2)]
    cipher = TinyARX_permutation("TinyARX", inp, out, nbr_rounds=r)
    cipher.post_initialization(copy_operator=copy_operator)
    return cipher
